apps/holiday_app/lib/holiday_app_web/router.ex
defmodule HolidayAppWeb.Router do
  use HolidayAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HolidayAppWeb.AuthPipeline
  end

  pipeline :auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", HolidayAppWeb do
    pipe_through :browser

    get "/", HomeController, :index
  end

  scope "/auth", HolidayAppWeb do
    pipe_through :browser

    get "/new", AuthController, :new
    get "/:provider", AuthController, :request
    post "/identity/callback", AuthController, :callback
    get "/:provider/callback", AuthController, :callback
  end

  scope "/", HolidayAppWeb do
    pipe_through [:browser, :auth]

    delete "/auth/logout", AuthController, :logout
    resources "/holidays", HolidayController
    resources "/users", UserController, except: [:delete]
  end

  scope "/admin", HolidayAppWeb do
    pipe_through [:browser, :auth, HolidayAppWeb.Plugs.EnsureAdmin]
  end
end

apps/holiday_app/lib/holiday_app_web/views/layout_view.ex
defmodule HolidayAppWeb.LayoutView do
  use HolidayAppWeb, :view
end

apps/holiday_app/lib/holiday_app_web/templates/layout/_header.html.eex
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">Holiday App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarMain">
    <%= if logged_in?(@conn) do %>
      <ul class="navbar-nav mr-auto">
        <%= nav_link(@conn, "Holidays", to: holiday_path(@conn, :index)) %>
        <%= nav_link(@conn, "Users", to: user_path(@conn, :index)) %>
      </ul>
      <ul class="navbar-nav">
        <%= nav_link(@conn, user_display_name(current_user(@conn)), to: user_path(@conn, :edit, current_user(@conn))) %>
        <%= nav_link(@conn, "Logout", to: auth_path(@conn, :logout), method: :delete) %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= nav_link(@conn, "Login", to: auth_path(@conn, :new)) %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

apps/holiday_app/lib/holiday_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= if @current_user do %>
      <%= tag :meta, name: "user_token", content: "#{current_token(@conn)}" %>
    <% end %>
    <title>Holidays</title>
  </head>

  <body>
    <%= render "_header.html", assigns %>

    <div class="container">
      <%= flash_alert(@conn, :info) %>
      <%= flash_alert(@conn, :error, :danger) %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>